config/routes.rb
Rails.application.routes.draw do

  resources :songs, only: [:index, :show, :new, :create, :edit, :update, :destroy]

end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to songs_path
    else
      render :new
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to song_path
    else
      render :edit
    end
  end

  def destroy
    @song = Song.destroy(params[:id])
    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:title, :songwriter, :performer)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FavoriteSongsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :performer %>
  <%= f.text_field :performer %>
  <br>
  <%= f.label :songwriter %>
  <%= f.text_field :songwriter %>
  <br>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<%= render "form" %>

app/views/songs/index.html.erb
<% @songs.each do |song| %>
  <%= song.title %>
  <br>
  <%= link_to "View Song Info", song_path(song) %>
  <br>
  <%= link_to "Edit Song Info", edit_song_path(song) %>
  <br>
  <%= link_to "Delete Song Record", song_path(song), method: "delete" %>
  <hr>
<% end %>
<%= link_to "Create New Song Record", new_song_path %>

app/views/songs/new.html.erb
<%= form_for @song do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :performer %>
  <%= f.text_field :performer %>
  <br>
  <%= f.label :songwriter %>
  <%= f.text_field :songwriter %>
  <br>
  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<p>
  Song title: <%= @song.title %>
</p>
<p>
  Performer: <%= @song.performer %>
</p>
<p>
  Songwriter: <%= @song.songwriter %>
</p>
<%= link_to "Back", songs_path %>